### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by VGBSR** [blaxxun-boop/TimedItemDestruction#2]
[Error  : Unity Log] KeyNotFoundException: The given key was not present in the dictionary.
Stack trace:
MonoMod.Cil.ILCursor.GotoNext (MonoMod.Cil.MoveType moveType, System.Func`2[Mono.Cecil.Cil.Instruction,System.Boolean][] predicates) (at <6733e342b5b549bba815373898724469>:0)
ItemDropDecayConfig.Hooks.ItemDropOnTimedDestruction (MonoMod.Cil.ILContext il) (at E:/Elliot/source/repos/Valheim/PaddysMods/ItemDropDecayConfig/Hooks.cs:23)
MonoMod.Cil.ILContext.Invoke (MonoMod.Cil.ILContext+Manipulator manip) (at <6733e342b5b549bba815373898724469>:0)
MonoMod.RuntimeDetour.ILHook+Context.InvokeManipulator (Mono.Cecil.MethodDefinition def, MonoMod.Cil.ILContext+Manipulator cb) (at <4e2760c7517c4ea79c633d67e84b319f>:0)
(wrapper dynamic-method) MonoMod.RuntimeDetour.ILHook+Context.DMD<MonoMod.RuntimeDetour.ILHook+Context::Refresh>(MonoMod.RuntimeDetour.ILHook/Context)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<MonoMod.RuntimeDetour.ILHook+Context::Refresh>?737660680(object)
HarmonyLib.Internal.RuntimeFixes.StackTraceFixes.OnILChainRefresh (System.Object self) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
MonoMod.RuntimeDetour.ILHook.Apply () (at <4e2760c7517c4ea79c633d67e84b319f>:0)
MonoMod.RuntimeDetour.ILHook..ctor (System.Reflection.MethodBase from, MonoMod.Cil.ILContext+Manipulator manipulator, MonoMod.RuntimeDetour.ILHookConfig& config) (at <4e2760c7517c4ea79c633d67e84b319f>:0)
MonoMod.RuntimeDetour.ILHook..ctor (System.Reflection.MethodBase from, MonoMod.Cil.ILContext+Manipulator manipulator, MonoMod.RuntimeDetour.ILHookConfig config) (at <4e2760c7517c4ea79c633d67e84b319f>:0)
MonoMod.RuntimeDetour.ILHook..ctor (System.Reflection.MethodBase from, MonoMod.Cil.ILContext+Manipulator manipulator) (at <4e2760c7517c4ea79c633d67e84b319f>:0)
MonoMod.RuntimeDetour.HookGen.HookEndpoint._NewILHook (System.Reflection.MethodBase from, MonoMod.Cil.ILContext+Manipulator to) (at <4e2760c7517c4ea79c633d67e84b319f>:0)
MonoMod.RuntimeDetour.HookGen.HookEndpoint._Add[TDelegate] (System.Func`3[T1,T2,TResult] gen, TDelegate hookDelegate) (at <4e2760c7517c4ea79c633d67e84b319f>:0)
MonoMod.RuntimeDetour.HookGen.HookEndpoint.Modify (System.Delegate hookDelegate) (at <4e2760c7517c4ea79c633d67e84b319f>:0)
MonoMod.RuntimeDetour.HookGen.HookEndpointManager.Modify (System.Reflection.MethodBase method, System.Delegate callback) (at <4e2760c7517c4ea79c633d67e84b319f>:0)
MonoMod.RuntimeDetour.HookGen.HookEndpointManager.Modify[T] (System.Reflection.MethodBase method, System.Delegate callback) (at <4e2760c7517c4ea79c633d67e84b319f>:0)
IL.ItemDrop.add_TimedDestruction (MonoMod.Cil.ILContext+Manipulator ) (at <b7fadb9015c147a48cff9a69a720239b>:0)
ItemDropDecayConfig.Hooks.Init () (at E:/Elliot/source/repos/Valheim/PaddysMods/ItemDropDecayConfig/Hooks.cs:17)
ItemDropDecayConfig.Main.Start () (at E:/Elliot/source/repos/Valheim/PaddysMods/ItemDropDecayConfig/Main.cs:38)

**Comment by blaxxun-boop** [comment]
The author of that mod lists his GitHub on Thunderstore: https://valheim.thunderstore.io/package/paddywan/ItemDropDecayConfig/

But since that mod hasn't been updated in almost 3 years now, I doubt that the author is still around to fix this issue.
May I recommend this perfectly working mod instead: https://valheim.thunderstore.io/package/Smoothbrain/TimedItemDestruction/

**Comment by VGBSR** [comment]
Hello, thank you for your answer and your time. Sorry I'm so stupid) thanks for the advice. sorry again
