### ISSUE TITLE
no longer works

### ISSUE THREAD

**Issue by BLUBBSON** [blaxxun-boop/TimedItemDestruction#3]
Currently installed BepInEx and Jotuun
The following error messages appear

[Error  : Unity Log] ArgumentNullException: Value cannot be null.
Parameter name: shader
Stack trace:
UnityEngine.Material..ctor (UnityEngine.Shader shader) (at <3aefadeb43334fcf8b7b268355c16be2>:0)
ShieldDomeImageEffect.Awake () (at <4efa3faf7157456487d70c5f7277dba7>:0)
[LogOutput.log](https://github.com/blaxxun-boop/TimedItemDestruction/files/15369014/LogOutput.log)

**Comment by blaxxun-boop** [comment]
TimedItemDestruction does not use shaders at all. Jotunn does, but this looks like a vanilla error message.
